import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import ThemeRegistry from './theme/ThemeRegistry'
import { LoginContextProvider } from './context/LoginContext'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <ThemeRegistry>
        <LoginContextProvider>
          <body className={inter.className}>{children}</body>
        </LoginContextProvider>
      </ThemeRegistry>
    </html>
  )
}
